title: ChippyCraft, LLC
email: mychippycraft@gmail.com
description: >-
  Modern-industrial, handcrafted infinity furniture. Functional art for inside and out.
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
