title: ChippyCraft, LLC
email: mychippycraft@gmail.com
description: >-
  Modern-industrial, handcrafted infinity furniture. Functional art for inside and out.
theme: jekyll-theme-cayman
markdown: kramdown
show_downloads: false
github:
  is_project_page: false
