title: ChippyCraft, LLC
email: mychippycraft@gmail.com
description: >-
  Modern-industrial, handcrafted infinity furniture. Functional art for inside and out.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
