title: ChippyCraft, LLC
email: mychippycraft@gmail.com
description: >
  Modern-industrial, handcrafted infinity furniture. Functional art for inside and out.
theme: jekyll-theme-midnight
markdown: kramdown
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
